import './globals.css'
import Nav from './Nav'
//import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
})

//export const metadata: Metadata = {
//  title: 'Create Next App',
//  description: 'Generated by create next app',
//}

//children means it will renderon every page

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {}
      <head />
      <body className={`mx-4 md:mx-48 xl:mx-96 ${roboto.variable} bg-gray-200`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
